import React from 'react';
import Head from 'next/head';
import HomePage from '@/src/screens/home/HomePage';
import { useRouter } from 'next/router';

export default function Home() {
  const path = useRouter();
  console.log(path);
  return (
    <>
      <Head>
        <title>Raddico App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
